inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - gemfiles/*.gemfile

Layout/ArgumentAlignment:
  Enabled: false
Layout/LineLength:
  Enabled: false
Layout/ParameterAlignment:
  Enabled: false

Naming/FileName:
  Exclude:
    - Appraisals

Style/AccessModifierDeclarations:
  Enabled: false
Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/BlockDelimiters:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/HashSyntax:
  Exclude:
    - Rakefile
Style/IfUnlessModifier:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/Next:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '[]'
Style/RaiseArgs:
  EnforcedStyle: compact
Style/SafeNavigation:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/SoleNestedConditional:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Metrics:
  Enabled: false
