inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true

Performance/RedundantBlockCall:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/BlockDelimiters:
  Enabled: false

Style/FileName:
  Exclude:
    - Appraisals

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - Rakefile

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/Next:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '[]'

Style/RaiseArgs:
  EnforcedStyle: compact

Style/SignalException:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Metrics:
  Enabled: false
